#!/usr/bin/env bash
# print text indefinetly, use sleep 2 in between each iteration
trap echo "Sigterm"
echo "I am invincible!"
x=0
while [ $x -eq  0 ]; do
	echo "To infinity and beyond"
	sleep 2
done

