#!/usr/bin/env bash
# while x is less than 100 print x, if a multiple of 3 print Fizz, if a multiple of 5 print Buzz, if both print FizzBuzz 
x=0
while [ $x -lt 100 ]; do
	((x++))
	if ! (( x % 3 )) && ! (( x % 5 )); then
		echo "FizzBuzz"
	elif ! (( x % 3 )); then
		echo "Fizz"
	elif ! (( x % 5 )); then
		echo "Buzz"
	else
		echo "$x"
	fi
done


