#!/usr/bin/bash/env bash
# while loop to print Best School 10 times, if statment to print Hi in line 9
x=1
while [ $x -le 9 ]
do
	echo "Best School"
	((x++))
	if [ $x == 9 ];
	then
		echo "Best School"
		echo "Hi"
	fi
done

