#!/usr/bin/bash/env bash
# while loop to print Best School, if then print bad luck line 4, elif to print good luck line 8
x=0
while [ $x -le 9 ]
do
	((x++))
	if [ $x -eq 4 ]
	then
		echo "bad luck"
		elif [ $x -eq 8 ]
		then 
			echo "good luck"
		else
			echo "Best School"
	fi
done

