#!/usr/bin/bash/env bash
x=0
while [ $x -lt 20 ]
do
	((x++))
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$x"
	esac
done
