#!/usr/bin/env bash
# while loop to print numbers 1-20, case to print bad luck at line 4, 9, 17.
x=0
while [ $x -lt 20 ]
do
	((x++))
	case $x in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$x"
	esac
done
